#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=off
  active_color=0xc0e2e2e3
  # active_color="gradient(top_left=0x88888888,bottom_right=11111111)"
  # active_color="glow(0x88888888)"
  # active_color=0x8049ff10
  # active_color=0x8010ff10
	inactive_color=0xc02c2e34
	background_color=0x302c2e34
  blacklist="sketchybar"
)

borders "${options[@]}"
