#echo .zprofile
#. ~/.paths

# [ -x ~/.zprofile_local ] && source ~/.zprofile_local

# Added by OrbStack: command-line tools and integration
# source ~/.orbstack/shell/init.zsh 2>/dev/null || :
# [ -x /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"
# [ -x /opt/homebrew/bin/brew ] && eval "export HOMEBREW_PREFIX_OPT=${HOMEBREW_PREFIX}/opt"
# [ -x /opt/homebrew/bin/brew ] && eval "export HOMEBREW_PREFIX_LIB=${HOMEBREW_PREFIX}/lib"
#
# [ -x /opt/homebrew/bin/brew ] && eval "export PATH=${HOMEBREW_PREFIX_OPT}/ruby/bin:$PATH"
# [ -x /opt/homebrew/bin/brew ] && eval "export PATH=${HOMEBREW_PREFIX_OPT}/curl/bin:$PATH"
# [ -x /opt/homebrew/bin/brew ] && eval "export PATH=${HOMEBREW_PREFIX_OPT}/llvm/bin:$PATH"

[ -f ~/.paths ] && source ~/.paths
if [ -x /opt/homebrew/bin/brew ] ; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  eval "export HOMEBREW_PREFIX_OPT=${HOMEBREW_PREFIX}/opt"
  eval "export HOMEBREW_PREFIX_LIB=${HOMEBREW_PREFIX}/lib"

  eval "export PATH=${HOMEBREW_PREFIX_OPT}/ruby/bin:$PATH"
  eval "export PATH=${HOMEBREW_PREFIX_OPT}/curl/bin:$PATH"
  eval "export PATH=${HOMEBREW_PREFIX_OPT}/llvm/bin:$PATH"
fi
