#echo .zshenv
# Skip the not really helping Ubuntu global compinit
skip_global_compinit=1
# eval "$(/opt/homebrew/bin/brew shellenv)"
# [ -f ~/.paths ] && source ~/.paths
# if [ -x /opt/homebrew/bin/brew ] ; then
#   eval "$(/opt/homebrew/bin/brew shellenv)"
#   eval "export HOMEBREW_PREFIX_OPT=${HOMEBREW_PREFIX}/opt"
#   eval "export HOMEBREW_PREFIX_LIB=${HOMEBREW_PREFIX}/lib"
#
#   eval "export PATH=${HOMEBREW_PREFIX_OPT}/ruby/bin:$PATH"
#   eval "export PATH=${HOMEBREW_PREFIX_OPT}/curl/bin:$PATH"
#   eval "export PATH=${HOMEBREW_PREFIX_OPT}/llvm/bin:$PATH"
# fi
export XDG_CONFIG_HOME=~/.config
export RIPGREP_CONFIG_PATH=~/.config/ripgrep/rc
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_BUNDLE_FILE=~/.config/brew/Brewfile
export EDITOR="nvim"
export ZK_NOTEBOOK_DIR=~/.notes/notebook
export NIX_CONF_DIR=~/.config/nix
export DFT_SKIP_UNCHANGED=true
export DOTBARE_DIR=~/.files.git
export DOTBARE_TREE=~
export TENV_AUTO_INSTALL=true
export EZA_CONFIG_DIR=./config/eza
[ -e ~/.zshenv_local ] && source ~/.zshenv_local
[ -f ~/.cargo/env    ] && source "$HOME/.cargo/env"
[ -f ~/.local/share/nvim/mason/packages/erg ] && export ERG_PATH=~/.local/share/nvim/mason/packages/erg

#AWSume alias to source the AWSume script
# alias awsume="source awsume"

#Auto-Complete function for AWSume
#Auto-Complete function for AWSume
# fpath=(~/.awsume/zsh-autocomplete/ $fpath)
