#echo .zshenv
# Skip the not really helping Ubuntu global compinit
skip_global_compinit=1
source ~/.paths
export RIPGREP_CONFIG_PATH=~/.config/ripgrep/rc
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_FILTERING=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export EDITOR="nvim"
