#echo .zshenv
# Skip the not really helping Ubuntu global compinit
skip_global_compinit=1
# eval "$(/opt/homebrew/bin/brew shellenv)"
# [ -f ~/.paths ] && source ~/.paths
# if [ -x /opt/homebrew/bin/brew ] ; then
#   eval "$(/opt/homebrew/bin/brew shellenv)"
#   eval "export HOMEBREW_PREFIX_OPT=${HOMEBREW_PREFIX}/opt"
#   eval "export HOMEBREW_PREFIX_LIB=${HOMEBREW_PREFIX}/lib"
#
#   eval "export PATH=${HOMEBREW_PREFIX_OPT}/ruby/bin:$PATH"
#   eval "export PATH=${HOMEBREW_PREFIX_OPT}/curl/bin:$PATH"
#   eval "export PATH=${HOMEBREW_PREFIX_OPT}/llvm/bin:$PATH"
# fi
export RIPGREP_CONFIG_PATH=~/.config/ripgrep/rc
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_BUNDLE_FILE=~/.config/brew/Brewfile
export EDITOR="nvim"
export ZK_NOTEBOOK_DIR=~/.notes/notebook
[ -e ~/.zshenv_local ] && source ~/.zshenv_local
[ -f ~/.cargo/env    ] && source "$HOME/.cargo/env"
[ -f ~/.local/share/nvim/mason/packages/erg ] && export ERG_PATH=~/.local/share/nvim/mason/packages/erg
