# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  #source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

# Disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="true"
# Disable colors in ls
DISABLE_LS_COLORS="true"
# Disable auto-setting terminal title
DISABLE_AUTO_TILE="true"
# Disable marking untracked files under VCS as dirty.
# This makes repository status checks for large repositories much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"
# Change the command execution time stamp shown in the history command output
# Optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"
# Disable initial powerlevel10k config wizard
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
#
export DISABLE_AUTO_TITLE='true'

#declare -A ZINIT
#ZINIT[COMPINIT_OPTS]="-C"
#ZINIT[OPTIMIZE_OUT_DISK_ACCESSES]=1
### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
  print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
  command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
  command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
    print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
    print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

if [[ ! -f $HOME/.zinit/bin/zinit.zsh.zwc ]]; then
  zinit self-update
fi

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
#zinit lucid nocd light-mode for \
#  zinit-zsh/z-a-rust \
#  zinit-zsh/z-a-as-monitor \
#  zinit-zsh/z-a-patch-dl \
#  zinit-zsh/z-a-bin-gem-node

###  Thom's environment
###
zinit wait"0" lucid is-snippet for \
  $HOME/.aliases \

zinit wait"2" lucid nocd is-snippet for \
  OMZ::lib/functions.zsh \
  OMZ::lib/misc.zsh \
  OMZ::lib/history.zsh \
  OMZ::lib/directories.zsh \
  OMZ::lib/git.zsh \
  OMZ::plugins/git/git.plugin.zsh \
  https://raw.githubusercontent.com/shihyuho/zsh-jenv-lazy/master/jenv-lazy.plugin.zsh \
  $HOME/.bash_local \
  $HOME/.dockerfunc
  #https://github.com/sainnhe/dotfiles/raw/master/.zsh-theme-gruvbox-material-dark \

#zinit load black7375/zsh-lazyenv

#zinit wait"8" lucid nocd is-snippet for \
  #OMZ::plugins/jenv/jenv.plugin.zsh
#zinit wait"1" lucid nocd light-mode for \
  #shihyuho/zsh-jenv-lazy

#zinit load zinit-zsh/z-a-bin-gem-node
#zinit ice from"gh-r" sbin"jenv"
#zinit load OMZ::plugins/jenv/jenv.plugin.zsh

#zinit wait"1" lucid nocd light-mode atload"zicompinit; zicdreplay" for \
zinit wait"1" lucid nocd light-mode for \
  zsh-users/zsh-autosuggestions \
  zdharma/fast-syntax-highlighting \
  hlissner/zsh-autopair

# zinit wait"1" lucid nocd light-mode for \
zinit wait"3" lucid nocd light-mode atload"zicompinit; zicdreplay" for \
  zsh-users/zsh-completions

if [[ ! -f $HOME/Library/Caches/sfdx/autocomplete/zsh_setup ]]; then
  # zinit wait"1" lucid nocd light-mode atload"zicompinit; zicdreplay" for \
  zinit wait"2" lucid nocd light-mode for \
    $HOME/Library/Caches/sfdx/autocomplete/zsh_setup
fi

# zinit wait lucid nocd light-mode for \
  # atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
    #zdharma/fast-syntax-highlighting \
  #blockf \
    #zsh-users/zsh-completions \
  #atload"!_zsh_autosuggest_start" \
    #zsh-users/zsh-autosuggestions \

[ -f /usr/local/share/zsh/site-functions/key-bindings.zsh ] && \
  zinit wait"1" lucid nocd is-snippet for \
    /usr/local/share/zsh/site-functions/key-bindings.zsh
    # latoabout/skim/shell/key-bindings.zsh
    # $HOME/.skim/shell/key-bindings.zsh

#zinit wait lucid nocd is-snippet for \

###  change directories without cd
###
setopt auto_cd

###  history config
###
setopt inc_append_history
setopt share_history              # share hsitory across instances
setopt hist_ignore_space          # ignore commands that start with space


PS1="READY > "
zinit wait"!" lucid nocd atload"!source ~/.p10k.zsh; _p9k_precmd" for \
  romkatv/powerlevel10k

# must be last
#zinit ice wait"3" lucid nocd atinit"zpcompinit; zpcdreplay"

function gi() { curl -sLw n https://www.gitignore.io/api/$@ ;}

#zprof
#zmodload -u zsh/zprof

### End of Zinit's installer chunk

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# OPS config
export OPS_DIR="$HOME/.ops"
export PATH="$HOME/.ops/bin:$PATH"
# source "$HOME/.ops/scripts/bash_completion.sh"
