###  Essentials ( Minimal )
brew "mas"
tap "buo/cask-upgrade"

###  terminal enhancements
###
brew "coreutils"
brew "curl"
brew "wget"
brew "lsd"

###  version control systems
###
brew "git"
brew "git-filter-repo"
brew "lazygit"
brew "svn"
cask "gitup"
brew "gh"
brew "gitui"
brew "git-delta"
brew "git-extras"

###  base build tools
brew "cmake"
brew "ninja"
brew "conan"
brew "llvm"

###  doucmentation generator
brew "doxygen"

###  search tools
###
brew "fd"
brew "ripgrep"
brew "tree"
brew "sk"
brew "the_silver_searcher"
brew "sd"
brew "bingrep"

###  cli testing
###
brew "hyperfine"

###  json utils
###
brew "jq"
brew "jql"
brew "jsonnet"
brew "jfrog-cli"

###  yaml utils
###
brew "yq"

###  nodejs
###
brew "node"
brew "yarn"
brew "pnpm"

###  neovim
###
brew "luajit"
brew "tree-sitter"
brew "neovim", args: ["HEAD"]
brew "editorconfig"

###  terminals
###
cask "alacritty"
cask "kitty"
brew "tmux"

###  java
###
cask "adoptopenjdk"

tap    "adoptopenjdk/openjdk"
  cask "adoptopenjdk8"

brew "jenv"

###  shell utilities
###
cask "day-o"
cask "hammerspoon"
tap    "koekeishiya/formulae"
  brew "yabai"
  brew "skhd"

###  note takers
###
cask "obsidian"

###  browsers
###
cask "chromium"
brew "chrome-cli"

###  ansible
###
brew "ansible"
brew "ansible-lint"

###  speed
###
brew "parallel"
brew "dsh"
brew "glances"
brew "htop"
brew "ctop"
brew "iftop"

###  Docker & K8s
###
cask "docker"
brew "whalebrew"
brew "docker-slim"

###  virtual machines
###
brew "terraform"
brew "terraform-docs"
brew "terraform-ls"
brew "tflint"
brew "packer"

###  Shell SCA Tools
brew "shellcheck"
brew "shfmt"

###  Go Language
###
brew "go"

###  language server protocol ( lsp )
###
brew "efm-langserver"
brew "gopls"
brew "rust-analyzer"
brew "deno"
brew "efm-langserver"
brew "bear"

###  Comms
###
cask "slack"
# cask "webex"

###  Kubernetes
###
brew "k9s"
cask "lens"
brew "helm"
brew "linkerd"
brew "terragrunt"

###  AWS Tools
###
brew "awscli"
brew "aws-okta"
brew "gimme-aws-creds"
brew "aws-iam-authenticator"
cask "session-manager-plugin"

###  Jenkins X
###
tap    "jenkins-x/jx"
  brew "jx"

###  Other Things
###
cask "vscodium"
brew "cowsay"
brew "dotenv-linter"

###  system utilities
###
brew "m-cli"

###  Documentation Tools
###
brew "mermaid-cli"
brew "pandoc"

###  Project Tools
###
mas "monday.com", id: 1298450641

###  fonts
###
brew "fontforge"
tap    "homebrew/cask-fonts"
  cask "font-xkcd"
  # cask "font-fira-code"
  cask "font-fira-code-nerd-font"
  # cask "font-fira-mono"
  cask "font-fira-mono-nerd-font"
  # cask "font-jetbrains-mono"
  cask "font-jetbrains-mono-nerd-font"
  # cask "font-victor-mono"
  cask "font-victor-mono-nerd-font"
  # cask "font-hack"
  cask "font-hack-nerd-font"
  cask "font-source-code-pro"
  cask "font-source-code-pro-for-powerline"
  cask "font-input"
  cask "font-sauce-code-pro-nerd-font"
  cask "font-ubuntu-nerd-font"
  cask "font-ubuntu-mono-nerd-font"
tap    "epk/epk"
  cask "font-sf-mono-nerd-font"
