-- local common = require 'lsp.common'

--  dotls configuration
--
--      yarn global add dot-language-server
--
-- local opts = {
--   on_attach = common.on_attach
--   , capabilities = common.capabilities
--   , flags = common.flags
-- }
--
-- return opts
