-- require 'lsp.lsp'
require 'lsp.go'
require 'lsp.efm'
require 'lsp.elm'
require 'lsp.lua'
require 'lsp.vim'
require 'lsp.cpp'
require 'lsp.css'
require 'lsp.bash'
require 'lsp.html'
require 'lsp.json'
require 'lsp.ruby'
require 'lsp.rust'
require 'lsp.yaml'
require 'lsp.docker'
require 'lsp.python'
require 'lsp.terraform'
require 'lsp.typescript'
-- require 'lsp.diagnostic'
