require 'lsp.handlers'.setup()

-- require 'lsp.lsp'
-- require 'lsp.go'
-- require 'lsp.zk'
-- require 'lsp.dot'
-- require 'lsp.efm'
-- require 'lsp.elm'
-- require 'lsp.lua'
-- require 'lsp.vim'
-- require 'lsp.cpp'
-- require 'lsp.css'
-- require 'lsp.xml'
-- require 'lsp.bash'
-- require 'lsp.html'
-- require 'lsp.json'
-- require 'lsp.rust'
-- require 'lsp.yaml'
-- require 'lsp.docker'
-- require 'lsp.python'
-- require 'lsp.sorbet'
-- require 'lsp.ansible'
-- require 'lsp.graphql'
require 'lsp.cucumber'
-- require 'lsp.fortran'
-- require 'lsp.emmet_ls'
-- require 'lsp.angularjs'
-- require 'lsp.terraform'
-- require 'lsp.typescript'
-- require 'lsp.diagnostic'
