#!/bin/zsh
# set -x

# yarn=(
#   neovim
# )

###  yarn retired
  # yaml-language-server

pnpm=(
  neovim
  cspell-cli
  vscode-langservers-extracted
  # @cucumber/language-server
  @microsoft/rush
  @stoplight/spectral-cli
  # @commitlint/{config-conventional,cli}
  # @commitlint/cli
  # @commitlint/config-conventional
    # commitlint-format-json
  jenni
  editorconfig-checker
  standard
  npm-groovy-lint
  @antora/cli
  @antora/site-generator
  textlint
    textlint-rule-no-todo
    textlint-rule-no-dead-link
    textlint-rule-editorconfig
    # textlint-plugin-markdown
)

###  pnpm retired
  # @angular/language-server
  # bash-language-server
  # diagnostic-languageserver
  # dockerfile-language-server-nodejs
  # dot-language-server
  # elm elm-test elm-format @elm-tooling/elm-language-server
  # emmet-ls
  # graphql-language-service-cli
  # pyright
  # typescript typescript-language-server
  # vim-language-server

# npm=(
#   graphql-language-service-cli
#   ansible-language-server
#   bash-language-server
#   dockerfile-language-server-nodejs
# )

pip=(
  neovim
  usort
  ocdc
  # ruff
  # fortran-language-server
)

###  pip retired
  # cmake-language-server

gem=(
  neovim
  cocoapods
  # sorbet
  standardrb
)

brew=(
  # hashicorp/tap/terraform-ls
  deno
  # gopls
  # rust-analyzer
  efm-langserver
  llvm
  bear
  mint-lang
  haskell-language-server
  # kotlin-language-server
  # black
  # hadolint
  composer
  cocoapods
  # ktlint
)

# luarocks=(
#   lanes
#   luacheck
# )


###  pip retired

# time yarn global add ${yarn// / }
# time yarn global upgrade --latest

time pnpm i  -g --loglevel error ${pnpm// / }
time pnpm up -g --loglevel error

time pipx upgrade-all
time pipx install ${pip// / }

time gem install --user-install ${gem// / }

# time luarocks install ${luarocks// / }
