#!/bin/zsh
# set -x

yarn=(
  yaml-language-server
  neovim
)

pnpm=(
  typescript typescript-language-server
  vscode-langservers-extracted
  dot-language-server
  pyright
  vim-language-server
  diagnostic-languageserver
  graphql-language-service-cli
  bash-language-server
  dockerfile-language-server-nodejs
  elm elm-test elm-format @elm-tooling/elm-language-server
  @angular/language-server
)

# npm=(
#   graphql-language-service-cli
#   bash-language-server
#   dockerfile-language-server-nodejs
# )

pip=(
  neovim
  fortran-language-server
  cmake-language-server
)

gem=(
  neovim
  sorbet
)

brew=(
  hashicopr/tap/terraform-ls
  deno
  gopls
  rust-analyzer
  efm-langserver
  llvm
  bear
)

time yarn global add ${yarn// / }
time yarn global upgrade --latest

time pnpm i  -g --loglevel error ${pnpm// / }
time pnpm up -g --loglevel error

time pip3 install -U ${pip// / }

time gem install --user-install ${gem// / }
